music = {
    "starboy" : "https://youtu.be/34Na4j8AVgA",
    "the box" : "https://youtu.be/UNZqm3dxd2w",
    "k for kabaradakkam" : "https://youtu.be/2vStL8V0CjQ",
    "hunter vantaar" : "https://youtu.be/zZYYQnE3U1k",
    "vikram title track" : "https://youtu.be/OKBMCL-frPU",
    "pathikichu" : "https://youtu.be/LUy4HCN9Uts",
    "blinding lights" : "https://youtu.be/fHI8X4OXluQ",
    "not like us" : "https://youtu.be/kQxc1J8Y0f0",
    "beat it" : "https://youtu.be/oRdxUFDoQe0",
    "way down we go" : "https://youtu.be/0-7IHOXkiV8",
    "jagadish on mission" : "https://youtu.be/DsQ-6AjPo3s",
    "the one retro" : "https://youtu.be/7DKfvuFz9Uc",
    "big dawgs" : "https://youtu.be/ehDLb6tV8zw",
    "athiradee" : "https://youtu.be/QjQSk2Jd3lU",
    "theemai dhaan vellum" : "https://youtu.be/6tdFhTX2s_k",
    "lokiverse theme" : "https://youtu.be/6YpjlNfV0qs",
    "houdini" : "https://youtu.be/jg4aNM9teT4",
    "fein" : "https://youtu.be/DKSkrm9AJz0",
    "billie jean" : "https://youtu.be/Zi_XLOBDo_Y",
    "everybody wants to rule the world" : "https://youtu.be/aGCdLKXNF3w",
    "six days" : "https://youtu.be/2S24-y0Ij3Y",
    "kadhal yaanai" : "https://youtu.be/Z81oPQ9GHEE",
    "happy nation" : "https://youtu.be/d73tiBBzvFM",
    "vaazhkai oru ottagam" : "https://youtu.be/dmM2E5ANsRk",
    "satisfya" : "https://youtu.be/IuVvNLjFbhA"
}
